[package]
name = "mmheroes-core"
version = "0.1.0"
authors = ["Sergej Jaskiewicz <jaskiewiczs@icloud.com>"]
edition = "2021"

[dependencies]
unicode-segmentation = "1.8.0"
assert_matches = "1.5.0"
bitflags = "2.6.0"

[features]
default = ["std"]
std = []
