[package]
name = "mmheroes"
version = "0.1.0"
authors = ["Sergej Jaskiewicz <jaskiewiczs@icloud.com>"]
edition = "2018"

[dependencies]
mmheroes-core = { path = "../mmheroes-core-rs" }
directories = "5.0.1"

[dependencies.pancurses]
version = "0.17.0"
features = ["win32"]
